#!/usr/bin/env bash
# Writes ios/Config/Secrets.xcconfig from the repo's .env.local (or the file
# given as $1). Only the browser-safe Supabase URL + anon key are copied.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
env_file="${1:-$here/../../.env.local}"
url="$(grep -E '^NEXT_PUBLIC_SUPABASE_URL=' "$env_file" | cut -d= -f2- | tr -d '"'"'"'')"
key="$(grep -E '^NEXT_PUBLIC_SUPABASE_ANON_KEY=' "$env_file" | cut -d= -f2- | tr -d '"'"'"'')"
if [[ -z "$url" || -z "$key" ]]; then
  echo "NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY missing in $env_file" >&2
  exit 1
fi
host="${url#https://}"; host="${host%/}"
# xcconfig treats // as a comment, so store the host only; the app adds https://
cat > "$here/../Config/Secrets.xcconfig" <<XC
// Generated by ios/scripts/write-secrets.sh — do not commit.
SUPABASE_HOST = $host
SUPABASE_ANON_KEY = $key
XC
echo "Wrote ios/Config/Secrets.xcconfig for $host"
